import type { CaptionStyle } from "./types";

export const STYLE_PRESETS: CaptionStyle[] = [
  {
    id: "bold-punch",
    name: "Bold Punch",
    fontFamily: "Arial",
    fontSize: 72,
    fontWeight: 800,
    fontStyle: "normal",
    letterSpacing: 0,
    primaryColor: "#ffffff",
    activeColor: "#f6e44d",
    outlineColor: "#080808",
    outlineWidth: 5,
    shadow: 2,
    position: "center",
    marginPercent: 10,
    verticalOffsetPercent: 0,
    uppercase: true,
    highlightActiveWord: true,
    transition: "pop",
    wordTimingOffsetMs: 120
  },
  {
    id: "clean-minimal",
    name: "Clean Minimal",
    fontFamily: "Helvetica Neue",
    fontSize: 62,
    fontWeight: 700,
    fontStyle: "normal",
    letterSpacing: 0,
    primaryColor: "#ffffff",
    activeColor: "#ffffff",
    outlineColor: "#111318",
    outlineWidth: 3,
    shadow: 1,
    position: "bottom",
    marginPercent: 12,
    verticalOffsetPercent: 0,
    uppercase: false,
    highlightActiveWord: false,
    transition: "fade",
    wordTimingOffsetMs: 120
  },
  {
    id: "electric",
    name: "Electric",
    fontFamily: "Arial Black",
    fontSize: 70,
    fontWeight: 900,
    fontStyle: "normal",
    letterSpacing: 1,
    primaryColor: "#ffffff",
    activeColor: "#7c5cff",
    outlineColor: "#11101a",
    outlineWidth: 5,
    shadow: 3,
    position: "center",
    marginPercent: 10,
    verticalOffsetPercent: 0,
    uppercase: true,
    highlightActiveWord: true,
    transition: "pop",
    wordTimingOffsetMs: 120
  },
  {
    id: "warm-story",
    name: "Warm Story",
    fontFamily: "Georgia",
    fontSize: 60,
    fontWeight: 700,
    fontStyle: "italic",
    letterSpacing: 0,
    primaryColor: "#fff8e8",
    activeColor: "#ff9d66",
    outlineColor: "#25160f",
    outlineWidth: 3,
    shadow: 2,
    position: "bottom",
    marginPercent: 14,
    verticalOffsetPercent: 0,
    uppercase: false,
    highlightActiveWord: true,
    transition: "fade",
    wordTimingOffsetMs: 120
  }
];
